#!/usr/bin/env bash
# Displays the content of the file /etc/passwd using while loopasswd

IFS=':'
while read -r user pass uid gid username_f homedir loginshell; do
      echo "The user $user is part of the $gid gang, lives in $homedir and rides $loginshell, $uid's place is protected by the passcode $pass, more info about the user here: $username_f"
done < "/etc/passwd"