#!/usr/bin/env bash
# Loops from 1 to 10 and:
# displays "bad luck" for the 4th loop iteration
# displays "good luck" for the 8th loop iteration
# displays "Best School" for all other iterations

count=0

while ((count < 10));
do
  if [ $count = 3 ]
  then
    echo "bad luck"
  elif [ $count = 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( count++ ))
done